runtime: python39

entrypoint: gunicorn bookhunt.wsgi

env_variables:
  SECRET_KEY: '<SECRET_KEY>'
  PORT: '8080'
  API_URL: '<API_URL>'
  API_KEY: '<API_KEY>'
  DEBUG: False
  DATABASE_URL: '<DATABASE_URL>'

handlers:
  - url: /static
    static_dir: static/
  - url: /.*
    script: auto
